### ISSUE TITLE
Relationship to libarchive-sys

### ISSUE THREAD

**Issue by dginev** [reset/libarchive-rust#2]
Hi,

I have been wishing for a great libarchive wrapper for Rust, and have on occasion helped with the [libarchive-sys](https://github.com/tz-lom/libarchive-sys) crate that tried that. Are you familiar with that repo?

I think tz-lom and myself, while very interested in using libarchive in Rust, both lack some of the expertise needed to write the perfect Rust wrapper, and probably aren't active enough to be maintainers either. I've seen you've already pushed to crates.io, which probably means you're serious about maintaining the wrapper in this repo. That would be awesome!

What I'm trying to figure out in this issue is whether I should switch over from libarchive-sys to this wrapper, so any extra information is most welcome. Thanks!

**Comment by reset** [comment]
@dginev hey! Yeah, I had seen the crate that tz-lom published before I did the work here. The abstraction wasn't exactly what I was looking for and we ran into some problems when implementing archive extraction with it in the project that drove the development on this crate, [Habitat](https://github.com/habitat-sh/habitat)

This is a core part of our larger open source project so yes, we plan to maintain this and keep it going!

**Comment by dginev** [comment]
Cool, thanks for the reply! I may have some time to revisit my libarchive component soon, maybe I manage to migrate it to your crate and send over any issues/tests that may be useful.

The only fundamental issue of the libarchive-sys crate is that it lacks active maintenance, which is quite useful for early stage crates. Given it took 3 months to get a reply on my comment I'm mildly worried this could affect the libarchvie-rust repo as well, but I'll keep my hopes up!

**Comment by reset** [comment]
@dginev I declared bankrupcy on my GitHub notifications when I joined Chef Software because, at the time, GitHub automatically subscribed you to notifications of every repository in an organization you were invited to. I've got them under control now ;)
