### ISSUE TITLE
On Crates.io the dependencies are wrong

### ISSUE THREAD

**Issue by radupopescu** [reset/libarchive-rust#3]
Hello,
The crates.io page of [libarchive](https://crates.io/crates/libarchive) lists `libarchive` itself as a dependency of the package. Shouldn't this be a dependency on `libarchive3-sys`?
Cheers,

**Comment by reset** [comment]
@radupopescu I do see a dependency on `libarchive3-sys` and not a self referencing dep. Can you share a screenshot maybe?

**Comment by radupopescu** [comment]
@reset I checked the page now. The problem I reported is gone. Maybe it was a momentary error?
In any case, now the dependency list is correct.

Thank you for looking into this.

**Comment by reset** [comment]
@radupopescu yeah it must have just been a view layer issue on their part!
